# NatureQuest Documentation Hub - Jekyll Configuration

title: NatureQuest Documentation Hub
description: Comprehensive documentation and learning roadmap for the NatureQuest ecosystem
author: NatureQuest Team
email: docs@naturequest.ai
url: https://docs.naturequest.ai
baseurl: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-include-cache

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..3
  parse_block_html: false
  parse_span_html: false

# Liquid settings
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Collections for each product
collections:
  devmentor:
    output: true
    permalink: /devmentor/:path/
  quizmentor:
    output: true
    permalink: /quizmentor/:path/
  harvest:
    output: true
    permalink: /harvest/:path/
  naturequest_auth:
    output: true
    permalink: /naturequest-auth/:path/
  infrastructure:
    output: true
    permalink: /infrastructure/:path/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "devmentor"
    values:
      layout: "product"
      product: "DevMentor"
  - scope:
      path: ""
      type: "quizmentor"
    values:
      layout: "product"
      product: "QuizMentor"
  - scope:
      path: ""
      type: "harvest"
    values:
      layout: "product"
      product: "Harvest.ai"
  - scope:
      path: ""
      type: "naturequest_auth"
    values:
      layout: "product"
      product: "NatureQuest Auth"
  - scope:
      path: ""
      type: "infrastructure"
    values:
      layout: "product"
      product: "Infrastructure"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Learning Roadmap
    url: /learning-roadmap/
  - title: DevMentor
    url: /devmentor/
  - title: QuizMentor
    url: /quizmentor/
  - title: Harvest.ai
    url: /harvest/
  - title: Auth
    url: /naturequest-auth/
  - title: Infrastructure
    url: /infrastructure/

# Search
search:
  enabled: true
  search_full_content: true

# Analytics (optional)
google_analytics: UA-XXXXXXXXX-X

# Social links
github_username: NatureQuest
twitter_username: naturequest

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .jekyll-cache
  - .gitignore
  - README.md
